export const API_ROUTES = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    registerVerify: '/auth/register/verify',
    registerResend: '/auth/register/resend',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    googleOtpStart: '/auth/google-otp/start',
    googleOtpVerify: '/auth/google-otp/verify',
  },
  projects: {
    base: '/projects',
    download: (id: string) => `/projects/${id}/download`,
    create: (id: string) => `/projects/${id}`,
  },
  teacher: {
    dashboard: '/teacher/dashboard',
    courses: '/teacher/courses',
    course: (id: string) => `/teacher/courses/${id}`,
    createCourseActivity: (id: string) => `/teacher/courses/${id}/activities`,
    deleteCourseActivity: (courseId: string, activityId: string) =>
      `/teacher/courses/${courseId}/activities/${activityId}`,
    courseActivityFeed: (id: string) => `/teacher/courses/${id}/activity-feed`,
    submissions: '/teacher/submissions',
    submission: (id: string) => `/teacher/submissions/${id}`,
    submissionNext: (id: string) => `/teacher/submissions/${id}/next`,
    notifications: '/teacher/notifications',
    badges: '/teacher/notifications/badges',
    threads: '/teacher/threads',
    thread: (id: string) => `/teacher/threads/${id}`,
    threadReplies: (id: string) => `/teacher/threads/${id}/replies`,
  },
  student: {
    courses: '/student/courses',
    coursesAvailable: '/student/courses/available',
    courseJoin: (id: string) => `/student/courses/${id}/join`,
    assignments: '/student/assignments',
    dashboard: '/student/dashboard',
    notifications: '/student/notifications',
    teacherRoleRequest: '/student/role-requests/teacher',
  },
} as const;
